Repository RAF-SI-2024/Banka-1-Mobile, pull requests merged in 2025-03, with the labels that each got.

#5 kostur gotov
  .gitignore
  README.md
  app.json
  app/_layout.tsx
  app/index.tsx
  assets/fonts/SpaceMono-Regular.ttf
  assets/images/adaptive-icon.png
  assets/images/favicon.png
  assets/images/icon.png
  assets/images/partial-react-logo.png
  assets/images/react-logo.png
  assets/images/react-logo@2x.png
  assets/images/react-logo@3x.png
  assets/images/splash-icon.png
  package-lock.json
  package.json
  tsconfig.json
Labels: size/XXL

#7 Napravljena profil stranica i stranica za verifikaciju
  app/(tabs)/_layout.tsx
  app/(tabs)/profile.tsx
  app/(tabs)/verification.tsx
  app/index.tsx
  package-lock.json
  package.json
Labels: lgtm, approved, size/L

#8 login povezan na back, verifikacija izmene
  app.json
  app/(tabs)/verification.tsx
  app/components/loginform.tsx
  app/services/axiosUser.ts
  package-lock.json
  package.json
Labels: lgtm, size/XL

#11 Zavrsena stranica moj profil, account carousel i axiosBanking
  app.json
  app/(tabs)/_layout.tsx
  app/(tabs)/home.tsx
  app/(tabs)/profile.tsx
  app/(tabs)/verification.tsx
  app/components/loginform.tsx
  app/services/axiosBanking.ts
  app/services/axiosUser.ts
Labels: lgtm, approved, size/XL
